### ISSUE TITLE
Forget reminder

### ISSUE THREAD

**Issue by Shashank3736** [ewliang/Remind-Me-Discord-Bot#2]
Whenever my bot restarts it forget about the reminders. Any solution for this

**Comment by sanelkukic** [comment]
I don't see this as being fixable because of the way the bot is coded. It's using `setTimeout()` which doesn't persist across restarts of the bot, so unless someone is up to the task of turning a simple reminders bot into something more complex using something like cron jobs then maybe, but I doubt anyone wants to put that kind of time and effort into a project that hasn't seen a single new commit in 2 years. /shrug

**Comment by Shashank3736** [comment]
ooff
